-- ! USE COM SABEDORIA.

DELETE FROM AUTOR_PLANTA;

DELETE FROM AUTOR;

DELETE FROM BASONIMO_PLANTA;

DELETE FROM BASONIMO;

DELETE FROM CATEGORIA;

DELETE FROM ESFERA;

DELETE FROM FAMILIA_BOTANICA;

DELETE FROM MUNICIPIO;

DELETE FROM PLANTA;

DELETE FROM TIPO_UNIDADE_CONSERVACAO;

DELETE FROM UNIDADE_CONSERVACAO_FEDERAL;

DELETE FROM UNIDADE_CONSERVACAO_MUNICIPIO;

DELETE FROM UNIDADE_CONSERVACAO;

DELETE FROM UNIDADE_FEDERAL;

DELETE FROM BIOMA_IBGE;