CREATE OR REPLACE PACKAGE BODY DYNAMIC IS
 /*
    */
    PROCEDURE INSERT_VALUES(
        RV_ARGS IN VARCHAR2,
        RV_VALUES IN VARCHAR2
    ) IS
        LV_ARGS      APEX_T_FLOW_VARCHAR;
        LV_STEATMENT VARCHAR2(32767);
    BEGIN
        LV_ARGS = UTILITY.EXPLODE(RV_ARGS, '.');
        IF LV_ARGS.COUNT < 2 THEN
            RAISE_APPLICATION_ERROR('Invalid parameters for INSERT_VALUES statement');
        END IF;
 --
        LV_STEATMENT := 'INSERT INTO '
    END;
END;